# Generated by Django 4.1.3 on 2022-12-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summoner_name', models.CharField(max_length=50)),
                ('summoner_level', models.IntegerField()),
                ('summoner_rank', models.CharField(default='Unranked', max_length=15)),
            ],
        ),
    ]
